'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PublicViewProfile

    '''<summary>
    '''frmProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmProfile As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''MessageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''NotificationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotificationButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''FriendButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FriendButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''MenuButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgIntroductionButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgIntroductionButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgStudyButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgStudyButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgJobButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgJobButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgSkillsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgSkillsButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgPicturesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgPicturesButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgPostsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgPostsButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgFriendsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgFriendsButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImgFavoritesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgFavoritesButton As Global.System.Web.UI.WebControls.ImageButton
End Class
